name: Pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install torchrecsys
      run: |
        python -m pip install .
        python -m pip install pytest
    - name: Test with pytest
      run: |
        pytest
